### ISSUE TITLE
Add Cancellation Support

### ISSUE THREAD

**Issue by aarondglover** [stanac/EasyCrypto#2]
Is there any chance you could consider adding some overloads to the `AesFileEncrytion` methods (and other encryption methods where it makes sense)  to accept a cancellation token in order to support cancellation. 

I just had a cursory glance at the code, I understand this change would touch a lot of methods, because ultimately you need to push the cancellation token all the way down to the method;

`internal static async Task EncryptAsync(CryptoRequest request)
`

but I think it is a worth while pursuit.

**Comment by stanac** [comment]
Hi @aarondglover 
It shouldn't be a problem to add cancellation token support, I am just wondering where would it make sense to add it. Maybe on all async methods? Once "base methods" have support for cancellation it should be easy just to propagate the token from all public methods (async or not). Please let me know what you think. I believe I can implement this in the next few days.

**Comment by aarondglover** [comment]
Hi @stanac 

I guess it makes sense to add cancellation support for any method (both async or sync) where the process could take some time to execute.

I don't think limiting cancellation support to only Async methods makes much sense, as it is plausible that a synchronous method is being wrapped in a Task and hence could be cancel-able from another thread etc. 

I think it comes down to a **Value vs Effort** question. Just about all methods which ultimately enter into some sort of tight loop are candidates for cancellation support.

My particular need at this very moment would be to have the Async Methods in the `AESFileEncryption` class support cancellation.

**Comment by stanac** [comment]
Hi @aarondglover you can try prerelease with token support from nuget https://www.nuget.org/packages/EasyCrypto/3.3.1-b I will upload actual release, but I need first to create a sample app and update docs and readme.

**Comment by aarondglover** [comment]
Am trying now. Thanks.

**Comment by aarondglover** [comment]
Works a treat. I did wonder why you introduced your own class (ReportAndCancellationToken) as opposed to using the standard cancellation tokens and implementing the standard IProgress Interface but it seems to work well enough and does allow you to extend the functionality with features such as defining the progress reporting intensity.

**Comment by stanac** [comment]
I believe methods already have too many parameters, their signatures are starting to look like something opposite of OOP, so I didn't want to have two additional parameters. Beside that I believe IProgress is too simple and less useful than custom object I'm using. I'm closing the ticket.
