### ISSUE TITLE
Question: Remove Salt and IV from stream

### ISSUE THREAD

**Issue by andrescastano** [stanac/EasyCrypto#3]
Hi, is there any way to remove the embedded salt and vector from the decrypted stream?

I am using this method to encrypt: AesEncryption.EncryptWithPassword.

**Comment by stanac** [comment]
Hi, sorry for late reply, I can't give you the answer right away, however will look into this later today.

**Comment by andrescastano** [comment]
Hi, i found that my problem was not an embedded salt, instead that the stream returned by the DecrypWithPassword method is at the end of the stream position. So i just seek to the beginning asn i could readi it.
